export interface Epoc
{
  id: number;
  enfermera: number;
  ugc: number;
  nuhsa: string;
  tipo_epoc:number;
  fecha_alta:string;
  fecha_com:string;
  contacto_48:number;
  tipo_visita:number;
  sat1:number;
  sat2:number;
  sat3:number;
  cat1:number;
  cat2:number;
  cat3:number;  
  gisps3_1:number;
  gisps3_2:number;
  gisps3_3:number;
  tto_inhalador1:number;
  tto_inhalador2:number;
  tto_inhalador3:number;
  alarma:number;
  fuma1:number;
  fuma2:number;
  fuma3:number;
  int_antitabaco:number;
  rehabilitacion:number;
  oxigeno1:number;
  oxigeno2:number;
  oxigeno3:number;
  disfagia1:number;
  disfagia2:number;
  disfagia3:number;
  gripe:number;
  neumococo:number;
  reingresos:number;
  agudizaciones:number;
  pap:number;
  fin_seguimiento: number;
  fecha_visita: string;
  procedencia: number;  
}
